/**:
  ros__parameters:
    gait:
      knee_orientation : "><"
      pantograph_leg : True
      odom_scaler: 1.0
      max_linear_velocity_x : 0.1
      max_linear_velocity_y : 0.05
      max_angular_velocity_z : 0.1
      com_x_translation : -0.05
      swing_height : 0.1
      stance_depth : 0
      stance_duration : 0.5
      nominal_height : 0.16