/**:
  ros__parameters:
    gait:
      knee_orientation : "><"
      pantograph_leg : True
      odom_scaler: 1.0 
      max_linear_velocity_x : 0.1 #0.1
      max_linear_velocity_y : 0.05 #0.05
      max_angular_velocity_z : 0.5 #0.1
      com_x_translation : -0.05 #0.0
      swing_height : 0.05 #0.05
      stance_depth : 0.0 #0.0
      stance_duration : 0.5 #0.5
      nominal_height : 0.16 #0.16